### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by grstavares** [davidmoten/aws-maven-plugin#2]
Hi David,

Anytime did ou get a NullPointer?? see this:

		<plugin>
			<groupId>com.github.davidmoten</groupId>
			<artifactId>aws-maven-plugin</artifactId>
			<version>${aws.maven.plugin.version}</version>
			<configuration>
				<awsAccessKey>${env.AWS_ACCESS_KEY_ID}</awsAccessKey>
				<awsSecretAccessKey>${env.AWS_SECRET_ACCESS_KEY}</awsSecretAccessKey>
				<artifact>${project.build.directory}/plazaz-backend.war</artifact>
				<applicationName>Plazaz</applicationName>
				<environmentName>beta</environmentName>
				<region>sa-east-1</region>
				<versionLabel>plazaz-backend-${maven.build.timestamp}.war</versionLabel>
			</configuration>
		</plugin>

`[ERROR] Failed to execute goal com.github.davidmoten:aws-maven-plugin:0.2.11:deployCf (default-cli) on project plazaz-backend: Execution default-cli of goal com.github.davidmoten:aws-maven-plugin:0.2.11:deployCf failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.davidmoten:aws-maven-plugin:0.2.11:deployCf (default-cli) on project plazaz-backend: Execution default-cli of goal com.github.davidmoten:aws-maven-plugin:0.2.11:deployCf failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.github.davidmoten:aws-maven-plugin:0.2.11:deployCf failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at com.github.davidmoten.aws.maven.CloudFormationDeployMojo.execute(CloudFormationDeployMojo.java:76)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
`

I'm trying to deploy to eb. As per the StackTrace it is calling the CloudFormationDeployer... It is right??

Best Regards,

Gustavo

**Comment by grstavares** [comment]
My Bad!! I was using the wrong command!!
